Repository hmcts/em-icp-api, pull requests merged in 2020-09, with the labels that each got.

#30 Remove terraform state
  .dockerignore
  .gitignore
  Dockerfile
  Jenkinsfile_nightly
  api/model/actions.ts
  api/model/httpError.ts
  api/model/participant.ts
  api/model/session.ts
  api/model/userInfo.ts
  api/redis.ts
  api/resources/localhost-ssl/README.md
  api/resources/localhost-ssl/localhost.crt
  api/resources/localhost-ssl/localhost.key
  api/router/routerFinder.ts
  api/routes/health.ts
  api/routes/sessions.ts
  api/security/idam-client.ts
  api/swagger.ts
  app.ts
  infrastructure/state.tf
  nodemon.json
  package-lock.json
  package.json
  server.ts
  socket.ts
  sonar-project.properties
  src/main/development.ts
  test/functional/sessions.test.ts
  test/functional/socket.test.ts
  test/functional/testUtil.ts
  test/smoke/healthcheck.test.ts
  test/unit/routes/sessions.test.ts
  test/unit/security/idam-client.test.ts
  tsconfig.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:em, prd:em, rel:em-icp-pr-30

#31 reinstate state file
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-icp-pr-31

#27 Em 2695 add participant list
  Jenkinsfile_nightly
  api/model/actions.ts
  api/model/interfaces.ts
  api/model/participant.ts
  api/model/session.ts
  api/model/userInfo.ts
  api/redis-client.ts
  api/redis.ts
  api/routes/health.ts
  api/routes/sessions.ts
  api/security/idam-client.ts
  api/swagger.ts
  app.ts
  charts/em-icp/Chart.yaml
  charts/em-icp/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/test.yaml
  docker-compose.yml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
  package.json
  server.ts
  socket.ts
  test/functional/socket.test.ts
  test/functional/testUtil.ts
  test/unit/redis-client.test.ts
  test/unit/routes/sessions.test.ts
  yarn.lock
Labels: ns:em, prd:em, rel:em-icp-pr-27

#32 use correct application type
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-icp-pr-32

#35 add em shared MI
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-icp-pr-35
