Repository hmcts/em-icp-api, pull requests merged in 2020-06, with the labels that each got.

#9 vault update
  README.md
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
Labels: ns:em, rel:em-icp-pr-9

#11 Add redis
  charts/em-icp/Chart.yaml
  charts/em-icp/requirements.yaml
  charts/em-icp/values.preview.template.yaml
  charts/em-icp/values.yaml
  infrastructure/main.tf
Labels: ns:em, rel:em-icp-pr-11

#12 empty to trigger a build
  infrastructure/main.tf
Labels: ns:em, rel:em-icp-pr-12

#14 update redis-password
  charts/em-icp/Chart.yaml
  charts/em-icp/values.preview.template.yaml
Labels: ns:em, rel:em-icp-pr-14

#15 Build redis
  charts/em-icp/Chart.yaml
  charts/em-icp/values.preview.template.yaml
  infrastructure/main.tf
Labels: ns:em, rel:em-icp-pr-15

#16 build redis into PRs
  charts/em-icp/Chart.yaml
  charts/em-icp/values.preview.template.yaml
  charts/em-icp/values.yaml
Labels: ns:em, rel:em-icp-pr-16

#13 Em 2945 icp backend
  .eslintignore
  .eslintrc.js
  .gitignore
  README.md
  bin/idam/idam-create-user.sh
  bin/idam/idam-get-s2s-token.sh
  bin/idam/idam-get-user-token.sh
  bin/idam/idam.sh
  bin/init.sh
  charts/em-icp/Chart.yaml
  charts/em-icp/values.yaml
  config/custom-environment-variables.yaml
  config/default.json
  config/default.yaml
  config/dev.json
  config/dev.yaml
  config/production.json
  config/test.json
  config/test.yaml
  docker-compose-dependencies.yml
  docker-compose.yml
  infrastructure/.gitignore
  infrastructure/output.tf
  jest.config.js
  package-lock.json
  package.json
  sonar-project.properties
  src/main/HttpError.ts
  src/main/app.ts
  src/main/development.ts
  src/main/httpError.ts
  src/main/models/Session.ts
  src/main/models/Sessions.ts
  src/main/models/actions.ts
  src/main/models/participant.ts
  src/main/models/session.ts
  src/main/models/userInfo.ts
  src/main/modules/helmet/index.ts
  src/main/router/routerFinder.ts
  src/main/routes/health.ts
  src/main/routes/sessions.ts
  src/main/security/idam-client.ts
  src/main/server.ts
  src/main/setupSecrets.ts
  src/main/socket.ts
  src/test/config.ts
  src/test/smoke/healthcheck.test.ts
  src/test/unit/health.test.ts
  src/test/unit/routes/health.test.ts
  src/test/unit/routes/sessions.test.ts
  src/test/unit/socket.test.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: ns:em, rel:em-icp-pr-13

#21 update capacity
  infrastructure/prod.tfvars
Labels: ns:em, prd:em, rel:em-icp-pr-21

#20 Em 2945 swagger docs
  package.json
  src/main/app.ts
  src/main/swagger.ts
  yarn.lock
Labels: ns:em, prd:em, rel:em-icp-pr-20

#22 Em 2945 tests
  Jenkinsfile_CNP
  bin/idam/idam-create-user.sh
  bin/idam/idam-get-s2s-token.sh
  bin/idam/idam-get-user-token.sh
  bin/idam/idam.sh
  config/custom-environment-variables.yaml
  config/default.yaml
  config/test.yaml
  docker-compose-dependencies.yml
  package-lock.json
  package.json
  src/main/app.ts
  src/main/routes/sessions.ts
  src/main/socket.ts
  src/test/config.ts
  src/test/functional/sessions.test.ts
  src/test/functional/socket.test.ts
  src/test/functional/testUtil.ts
  src/test/smoke/healthcheck.test.ts
  src/test/unit/routes/health.test.ts
  src/test/unit/routes/sessions.test.ts
  src/test/unit/socket.test.ts
  yarn.lock
Labels: ns:em, prd:em, rel:em-icp-pr-22

#23 add some api GW conf
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-icp-pr-23

#24 add some api GW conf different method
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-icp-pr-24
