Repository hmcts/em-icp-api, pull requests merged in 2022-02, with the labels that each got.

#242 added suppression for ICP
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-icp-pr-242

#243 suppress vulnerabilities
  yarn-audit-known-issues
Labels: ns:em, prd:em, rel:em-icp-pr-243

#245 Update dependencies to resolve CVE's
  package.json
  yarn.lock
Labels: ns:em, prd:em, rel:em-icp-pr-245

#247 Update dependencies to resolve CVE's
  .eslintrc.js
  package.json
  yarn.lock
Labels: ns:em, prd:em, rel:em-icp-pr-247
