Repository hmcts/em-icp-api, pull requests merged in 2023-10, with the labels that each got.

#870 fix build
  .github/renovate.json
  yarn-audit-known-issues
Labels: prd:em, ns:em, rel:em-icp-pr-870

#855 Migrate redis cache to Basic sku in non-prod env
  .github/renovate.json
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: prd:em, destroy, ns:em, rel:em-icp-pr-855

#871 comment out infrastructure
  infrastructure/main.tf
  infrastructure/output.tf
Labels: prd:em, destroy, ns:em, rel:em-icp-pr-871
