Repository hmcts/em-icp-api, pull requests merged in 2023-06, with the labels that each got.

#519 Upgrade Redis Version to 6
  infrastructure/main.tf
  yarn-audit-known-issues
Labels: ns:em, prd:em, add-or-update, rel:em-icp-pr-519

#522 is string not number
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-icp-pr-522

#530 further changes for rebuilding
  infrastructure/main.tf
Labels: add-or-update

#531 Updated capacity for redis
  infrastructure/main.tf
Labels: ns:em, prd:em, destroy, rel:em-icp-pr-531
