Repository hmcts/em-icp-api, pull requests merged in 2024-06, with the labels that each got.

#1176 audit issue update
  yarn-audit-known-issues
  yarn.lock
Labels: prd:em, ns:em, rel:em-icp-pr-1176

#1195 Revert "Revert "EM-6025 changes for Resolving PED caseId & list of followers issue""
  api/em-web-pub-event-handler-options.ts
  api/model/interfaces.ts
  api/redis-client.ts
  api/routes/sessions.ts
  api/swagger.ts
  socket.ts
  test/unit/redis-client.test.ts
Labels: prd:em, ns:em, rel:em-icp-pr-1195

#1200 Em 6089 sync perftest
  Jenkinsfile_CNP
Labels: prd:em, ns:em, rel:em-icp-pr-1200

#1208 add redis cache
  infrastructure/main.tf
Labels: prd:em, ns:em, aat/add-or-update, prod/no-changes, rel:em-icp-pr-1208

#1219 changes for event handler url
  infrastructure/main.tf
Labels: prd:em, ns:em, aat/add-or-update, prod/add-or-update, rel:em-icp-pr-1219

#1221 Em 6089 terraform changes
  infrastructure/main.tf
Labels: prd:em, ns:em, aat/add-or-update, prod/add-or-update, rel:em-icp-pr-1221
