Repository hmcts/em-icp-api, pull requests merged in 2024-07, with the labels that each got.

#1234 Removed redundant apim lines
  infrastructure/main.tf
Labels: prd:em, ns:em, aat/destroy, prod/destroy, rel:em-icp-pr-1234

#1260 #EM-6134: logging changes
  api/em-web-pub-event-handler-options.ts
  app.ts
Labels: prd:em, ns:em, rel:em-icp-pr-1260

#1261 connection string is required instead key
  infrastructure/main.tf
Labels: prd:em, ns:em, aat/add-or-update, prod/add-or-update, rel:em-icp-pr-1261
